substitutions:
  name: esphome-web-d8eb9c
  friendly_name: ESPHome Web d8eb9c

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
#web_server:

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      inverted: true
      mode:
        input: true
        pullup: true 
    name: "gpio13"
  - platform: gpio
    pin:
      number: 14
      inverted: true
      mode:
        input: true
        pullup: true 
    name: "gpio14"
sensor:
  - platform: pulse_counter
    pin:
      number: 27
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Pin27"
    total:
      unit_of_measurement: 'L'
      name: '27Volume'